### ISSUE TITLE
Testing can't handle large KG. Giving CUDA out of memory error. 

### ISSUE THREAD

**Issue by rajiv256** [thunlp/OpenKE#209]
Hi, 
I am trying to train the TransE model on the FB2M dataset. However, due to a large number of its entities (2Million), the `Tester` module is giving CUDA out of memory error. My GPU has 12GB memory. However, the `Trainer` function works fine. Is there something I can do to make the `Tester` work? 

Thanks for the help. I will post the error logs in case you need them.

**Comment by rajiv256** [comment]
I tried with a GPU with more memory (16GB) and I was able to solve the above error. But the testing process is very slow since there is no parallelization.

**Comment by mistborn17** [comment]
@rajiv256 , How long did it take to train/test ?

**Comment by mistborn17** [comment]
@rajiv256 , how many relations/edges did you have?

**Comment by LiuYuemei111** [comment]
> I tried with a GPU with more memory (16GB) and I was able to solve the above error. But the testing process is very slow since there is no parallelization.

The current implementation version haven't provided an efficient support for large-scale test data. This problem will be solved in the next version. We are developing a parallelized version to handle large-scale KG.

**Comment by YBAgg** [comment]
> > I tried with a GPU with more memory (16GB) and I was able to solve the above error. But the testing process is very slow since there is no parallelization.
> 
> The current implementation version haven't provided an efficient support for large-scale test data. This problem will be solved in the next version. We are developing a parallelized version to handle large-scale KG.

Has this parallelized version been released yet, I also have trouble in train large-scale KG.

```
The toolkit is importing datasets.
The total of relations is 1.
The total of entities is 355722.
The total of train triples is 16217471.
... ...
RuntimeError: CUDA out of memory. Tried to allocate 314.16 GiB (GPU 0; 23.69 GiB total capacity; 11.26 GiB already allocated; 10.34 GiB free; 11.27 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```
